### ISSUE TITLE
m flag request

### ISSUE THREAD

**Issue by iorixxx** [Zeesky-code/Word-Count#2]
Hi Zainab thank your for your code. It would be great if you could implement -m flag too.

 -m      The number of characters in each input file is written to the
             standard output.  If the current locale does not support multibyte
             characters, this is equivalent to the -c option.  This will cancel
             out any prior usage of the -c option.

**Comment by Zeesky-code** [comment]
I have implemented the -m flag in the latest commit:
[911f19d](https://github.com/Zeesky-code/Word-Count/commit/911f19d5532ffa08846c6d32cff8695ddd2d45c8)

I'll be closing the issue as completed.
